# Generated by Django 5.2.6 on 2025-10-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('user_pd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_desc', models.TextField(blank=True, null=True)),
                ('task_status', models.BooleanField(default=False)),
                ('task_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='crud_task.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='p_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='crud_task.user'),
        ),
    ]
