# Generated by Django 5.2.6 on 2025-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_duration',
            field=models.DurationField(blank=True, help_text='Durée estimée (HH:MM:SS)', null=True),
        ),
    ]
