# Generated by Django 5.2.6 on 2025-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0002_task_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_log',
            field=models.BooleanField(default=False),
        ),
    ]
