# Generated by Django 5.2.6 on 2025-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0003_user_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
