# Generated by Django 5.2.6 on 2025-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0004_alter_user_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_finish',
            field=models.BooleanField(default=False),
        ),
    ]
