# Generated by Django 5.2.6 on 2025-10-06 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0005_task_task_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
