# Generated by Django 5.2.6 on 2025-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0006_task_task_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
